### ISSUE TITLE
uploading files issue

### ISSUE THREAD

**Issue by billyfung** [jinpark/podcast#20]
so with larger uploads, we get timeout errors because of how heroku handles the request.

**Comment by billyfung** [comment]
https://devcenter.heroku.com/articles/s3-upload-python

**Comment by jinpark** [comment]
So the problem here is that we're routing this through django instead of uploading directly to s3. I would like to keep it like that since we get the django features for files. I THINK we should be able to handle this through heroku somehow

**Comment by billyfung** [comment]
still not sure the best way to get around this.

currently im uploading directly to s3, and then having to use django-admin to update and link to db

**Comment by jinpark** [comment]
maybe we should just get off heroku 
but keep using heroku pg

**Comment by billyfung** [comment]
shall we switch to aws? before or after zappa trial

**Comment by billyfung** [comment]
closing this for now, using smaller files is a good workaround
