### ISSUE TITLE
Integrate circle ci to run tests and push to heroku

### ISSUE THREAD

**Issue by jinpark** [jinpark/podcast#9]
https://circleci.com/docs/1.0/continuous-deployment-with-heroku/

**Comment by billyfung** [comment]
you have all the heroku credentials? API key and what not?

**Comment by jinpark** [comment]
didnt i add you as a contributor on heroku?

**Comment by billyfung** [comment]
also with circle ci, how can I add a project if I'm only a collaborator on github? i can't see a straightforward way to do it
